costs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^documents/(?P<pk>\d+)/compare/(?P<other_pk>\d+)$', views.compare_document, name='compare-document'),
    url(r'^documents/(?P<pk>\d+)',
        views.detail_document,
        name='detail-document'),
    url(r'^documents$',
        views.list_documents,
        name='list-documents'),
    url(r'^services/(?P<pk>\d+)$', views.detail_service, name='detail-service'),
]

transparency/urls.py
from django.conf.urls import include, url
import django.contrib.auth.views
from transparency.admin import admin_site
import costs.urls
import publicsite.urls
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', include(admin_site.urls)),
    url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout'),
#    url(r'^admin/', include(admin_site.urls)),
    url(r'^costs/', include(costs.urls)),
    url(r'^public/', include(publicsite.urls)),
    url(r'^$', RedirectView.as_view(
        pattern_name='public-index', permanent=False)),
]

costs/models.py
import datetime
from itertools import chain

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models, transaction
from django.db.models import Sum

import markdown


class Document(models.Model):
    """ A document is a scenario or a record from facts, on 1 month.
    """
    TYPE_PUBLIC = 'fact'
    TYPE_DRAFT = 'plan'

    name = models.CharField('Nom', max_length=130)
    comment = models.TextField(
        'commentaire',
        blank=True, help_text="Texte brut ou markdown")
    comment_html = models.TextField(blank=True, editable=False)
    date = models.DateField(
        default=datetime.datetime.now,
        help_text="Date de création du document")
    type = models.CharField(max_length=10, choices=(
        (TYPE_PUBLIC, 'Rapport public'),
        (TYPE_DRAFT, 'Rapport brouillon'),
    ), help_text="Un rapport brouillon n'est pas visible publiquement")

    class Meta:
        ordering = ['-date']
        verbose_name = 'Rapport'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.comment_html = markdown.markdown(self.comment)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('detail-document', kwargs={'pk': self.pk})

    def copy(self):
        """ Deep copy and saving of a document

        All related resources are copied.
        """
        with transaction.atomic():
            new_doc = Document.objects.get(pk=self.pk)
            new_doc.pk = None
            new_doc.name = 'COPIE DE {}'.format(new_doc.name)
            new_doc.type = Document.TYPE_DRAFT
            new_doc.save()

            new_services, new_costs, new_goods = {}, {}, {}

            to_copy = (
                (self.service_set, new_services),
                (self.good_set, new_goods),
                (self.cost_set, new_costs),
            )

            for qs, index in to_copy:
                for item in qs.all():
                    old_pk = item.pk
                    item.pk = None
                    item.document = new_doc
                    item.save()
                    index[old_pk] = item

            to_reproduce = (
                (ServiceUse, new_services),
                (GoodUse, new_goods),
                (CostUse, new_costs),
            )

            for Klass, index in to_reproduce:
                src_qs = Klass.objects.filter(service__document=self)
                for use in src_qs.all():
                    use.pk = None
                    use.service = new_services[use.service.pk]
                    use.resource = index[use.resource.pk]
                    use.save()

            return new_doc

    def get_total_recuring_costs(self):
        return self.cost_set.aggregate(sum=Sum('price'))['sum'] or 0

    def get_total_goods(self):
        return self.good_set.aggregate(sum=Sum('price'))['sum'] or 0

    def compare(self, other_doc):
        """ Compare this document to another one

        :type other_doc: Document
        :rtype: dict
        """
        service_records = []
        for service in self.service_set.subscribables():
            other_service = Service.objects.similar_to(service).filter(
                document=other_doc).first()

            if other_service:
                deltas  = service.compare(other_service)
            else:
                deltas = {}

            service_records.append({
                'service': service,
                'other_service': other_service,
                'deltas': deltas,
            })

        comparison = {
            'services': service_records,
            'total_recuring_costs': self.get_total_recuring_costs() - other_doc.get_total_recuring_costs(),
            'total_goods': self.get_total_goods() - other_doc.get_total_goods(),
        }

        return comparison


class AbstractItem(models.Model):
    name = models.CharField('Nom', max_length=130)
    description = models.TextField('description', blank=True)
    description_html = models.TextField(blank=True)
    document = models.ForeignKey(Document)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.description_html = markdown.markdown(self.description)
        super().save(*args, **kwargs)

    class Meta:
        abstract = True


class AbstractResource(AbstractItem):
    UNIT_AMP = 'a'
    UNIT_MBPS = 'mbps'
    UNIT_U = 'u'
    UNIT_IPV4 = 'ipv4'
    UNIT_ETHERNET_PORT = 'eth'
    UNIT_SERVICE = 'services'

    capacity_unit = models.CharField(
        'unité',
        max_length=10,
        choices=(
            (UNIT_AMP, 'A'),
            (UNIT_MBPS, 'Mbps'),
            (UNIT_U, 'U'),
            (UNIT_IPV4, 'IPv4'),
            (UNIT_ETHERNET_PORT, 'ports'),
            (UNIT_SERVICE, 'abonnement'),
        ),
        blank=True,
        help_text="unité de capacité (si applicable)",
    )
    total_capacity = models.FloatField(
        'Capacité totale',
        default=1,
        help_text="Laisser à 1 si non divisible")

    class Meta:
        abstract = True

    def get_use_class(self):
        raise NotImplemented

    def used(self, except_by=None):
        """ Return the used fraction of an item

        :type: Service
        :param except_by: exclude this service from the math
        :rtype: float
        """
        sharing_costs = self.get_use_class().objects.filter(resource=self)
        if except_by:
            sharing_costs = sharing_costs.exclude(service=except_by)

        existing_uses_sum = sum(
            sharing_costs.values_list('share', flat=True))

        return existing_uses_sum

    def used_fraction(self, *args, **kwargs):
        return self.used(*args, **kwargs)/self.total_capacity

    def unused(self):
        return self.total_capacity-self.used()

    def __str__(self):
        if self.capacity_unit == '':
            return self.name
        else:
            return '{} {:.0f} {}'.format(
                self.name, self.total_capacity,
                self.get_capacity_unit_display())


class Cost(AbstractResource):
    """ A monthtly cost we have to pay
    """
    price = models.FloatField("Coût mensuel")

    def get_use_class(self):
        return CostUse

    class Meta:
        verbose_name = 'Coût mensuel'


class GoodQuerySet(models.QuerySet):
    def monthly_provision_total(self):
        # FIXME: could be optimized easily
        return sum([i.monthly_provision() for i in self.all()])


class Good(AbstractResource):
    """ A good, which replacement is provisioned
    """
    price = models.FloatField("Prix d'achat")
    provisioning_duration = models.DurationField(
        "Durée d'amortissement",
        choices=settings.PROVISIONING_DURATIONS)

    objects = GoodQuerySet.as_manager()

    def get_use_class(self):
        return GoodUse

    def monthly_provision(self):
        return self.price/self.provisioning_duration.days*(365.25/12)

    class Meta:
        verbose_name = "Matériel ou Frais d'accès"
        verbose_name_plural = "Matériels ou Frais d'accès"


class AbstractUse(models.Model):
    share = models.FloatField()
    service = models.ForeignKey('Service')
    help = models.TextField(
        'Aide',
        blank=True, help_text="Texte brut ou markdown")

    class Meta:
        abstract = True

    def __str__(self):
        return str(self.resource)

    def clean(self):
        if hasattr(self, 'resource'):
            usage = self.resource.used(except_by=self.service) + self.share
            if usage > self.resource.total_capacity:
                raise ValidationError(
                    "Cannot use more than 100% of {})".format(self.resource))

    def real_share(self):
        """The share, + wasted space share

        Taking into account that the unused space is
        wasted and has to be divided among actual users
        """
        return (
            self.share +
            (self.share/self.resource.used())*self.resource.unused()
        )

    def unit_share(self):
        if self.service.subscriptions_count == 0:
            return 0
        else:
            return self.share/self.service.subscriptions_count

        return

    def unit_real_share(self):
        if self.service.subscriptions_count == 0:
            return 0
        else:
            return self.real_share()/self.service.subscriptions_count

    def value_share(self):
        return (
            self.resource.price
            * self.real_share()
            / self.resource.total_capacity
        )

    def unit_value_share(self):
        if self.service.subscriptions_count == 0:
            return 0
        else:
            return self.value_share()/self.service.subscriptions_count


class CostUse(AbstractUse):
    resource = models.ForeignKey(Cost)

    class Meta:
        verbose_name = 'Coût mensuel associé'
        verbose_name_plural = 'Coûts mensuels associés'

    def cost_share(self):
        return (
            self.real_share() / self.resource.total_capacity
            * self.resource.price
        )

    def unit_cost_share(self):
        subscriptions_count = self.service.subscriptions_count
        if subscriptions_count == 0:
            return 0
        else:
            return self.cost_share()/self.service.subscriptions_count


class GoodUse(AbstractUse):
    resource = models.ForeignKey(Good)

    class Meta:
        verbose_name = "Matériel ou frais d'accès utilisé"
        verbose_name_plural = "Matériels et frais d'accès utilisés"

    def monthly_provision_share(self):
        return (
            self.real_share()
            * self.resource.monthly_provision()
            / self.resource.total_capacity)

    def unit_monthly_provision_share(self):
        subscriptions_count = self.service.subscriptions_count
        monthly_share = self.monthly_provision_share()
        if subscriptions_count == 0:
            return 0

costs/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404

from .models import Document, Service, ServiceUse, CostUse, GoodUse


CONTENT_TYPES = {
    'html': 'text/html; charset=utf-8',
    'txt': 'text/plain; charset=utf-8',
}

def format_to_content_type(_format):
    if _format not in ('txt', 'html'):
        raise ValueError('Unknown format {}'.format(_format))
    else:
        return '{}; charset=utf-8'.format(CONTENT_TYPES[_format])

@login_required
def list_documents(request):
    breadcrumbs = (
        ('Rapports', reverse('list-documents')),
    )
    docs = Document.objects.all()\
                           .prefetch_related('service_set')\
                           .order_by('-date')

    return render(
        request, 'costs/documents_list.html', {
            'documents': docs,
            'planning_documents': docs.filter(type=Document.TYPE_DRAFT),
            'factual_documents': docs.filter(type=Document.TYPE_PUBLIC),
            'breadcrumbs': breadcrumbs,
        })


@login_required
def detail_document(request, pk):
    doc = get_object_or_404(Document, pk=pk)

    breadcrumbs = (
        ('Rapports', reverse('list-documents')),
        (str(doc), doc.get_absolute_url())
    )
    return render(
        request, 'costs/document_detail.html', {
            'document': doc,
            'other_documents': Document.objects.exclude(pk=doc.pk),
            'breadcrumbs': breadcrumbs,
            'total_recuring_costs': doc.get_total_recuring_costs(),
            'total_goods': doc.get_total_goods()
        })

@login_required
def compare_document(request, pk, other_pk):
    _format = request.GET.get('format', 'html')

    if _format not in ('html', 'txt'):
        return HttpResponseBadRequest('Wrong format : {}'.format(_format))

    doc = Document.objects.get(pk=pk)
    other_doc = Document.objects.get(pk=other_pk)

    breadcrumbs = (
        ('Rapports', reverse('list-documents')),
        (str(doc), doc.get_absolute_url()),
        ('Variations depuis {}'.format(other_doc), request.path),
    )
    context = {
        'breadcrumbs': breadcrumbs,
        'document': doc,
        'other_document': other_doc,
        'other_documents': Document.objects.exclude(pk=doc.pk),
        'deltas': doc.compare(other_doc),
    }
    response = render(
        request,
        'costs/document_compare.{}'.format(_format),
        context,
        content_type=format_to_content_type(_format),
    )
    return response


@login_required
def detail_service(request, pk):
    service = Service.objects.get(pk=pk)

    doc = service.document
    breadcrumbs = (
        ('Rapports', reverse('list-documents')),
        (str(doc), doc.get_absolute_url()),
        (service.name, service.get_absolute_url())
    )
    costs_uses = CostUse.objects.filter(service=service)
    goods_uses = GoodUse.objects.filter(service=service)
    services_uses = ServiceUse.objects.filter(service=service)

    context = {}
    context.update(service.get_prices())
    context.update({
        'breadcrumbs': breadcrumbs,
        'document': doc,
        'service': service,
        'costs_uses': costs_uses,
        'goods_uses': goods_uses,
        'services_uses': services_uses,
    })
    return render(request, 'costs/service_detail.html', context)

costs/templates/costs/document_compare.html
{% extends "costs/document_detail.html" %}

{% load costs %}

{% block content %}

<section class="text container ui row">
    <div class="ui icon message">
        <i class="time icon"></i>
        <p>
            Cette page présente les chiffres de <a href="{{ document.get_absolute_url }}">{{ document }}</a>
            ; les étiquettes indiquent les variations depuis <a href="{{ other_document.get_absolute_url }}">{{ other_document }}</a>.
        </p>
    </div>
</section>
<table class="ui structured table">
  <thead>
    <tr>
      <th>Service</th><th>Coût mensuel par abonnement</th>
      <th>Nb. abonnements</th>
    </tr>
  </thead>
  <tbody>
{% for service_record in deltas.services %}
      <tr>
          <td>
              <a href="{{ service_record.service.get_absolute_url }}">
              {{ service_record.service.name }}
              {% if not service_record.other_service %}<span class="ui horizontal label">NEW</span{% endif %}
              </a>
          </td>
          <td >
            {{ service_record.service.get_prices.unit_consolidated_cost|price }}
            {% if service_record.other_service %}
               {% with service_record.deltas.unit_consolidated_cost as consolidated_price_diff %}
                 {% if consolidated_price_diff != 0 %}
                   <span class="ui tag label">
                     {{ service_record.deltas.unit_consolidated_cost|price_diff }}
                   </span>
                 {% endif %}
               {% endwith %}
            {% endif %}
          </td>
          <td>
            {{ service_record.service.subscriptions_count }}
            {% if service_record.other_service %}
              {% with service_record.deltas.subscriptions_count as subscriptions_count_diff %}
                {% if subscriptions_count_diff != 0 %}
                  <span class="ui tag label">{{ subscriptions_count_diff|int_diff }}</span>
                {% endif %}
              {% endwith %}
            {% endif %}
          </td>

  </tr>
{% empty %}
  <tr><td>Pas de service pour l'instant.</td></li>
{% endfor %}
  </tbody>
  </table>
</section>

{% endblock %}

costs/templates/costs/document_detail.html
{% extends "base.html" %}

{% load costs %}


{% block rail %}

{% if document.comment_html %}

<div class="ui segment">
  <p>
    <a class="ui ribbon left label">Notes</a>
{{ document.comment_html|safe }}
  </p>
</div>
{% endif %}

<div class="ui vertical fluid menu">
{% if request.user.is_staff %}
<a href="{% url 'admin:costs_document_change' document.id %}" class="item">
  <i class="edit icon"></i>
    Éditer dans l'admin
</a>
{% endif %}

  <div class="item">
      <div class="ui simple dropdown">
      Comparer à…
          <ul class="menu">
          {% for i in other_documents %}
              <li class="item"><a href="{% url 'compare-document' document.pk i.pk %}">{{ i.name }}</a></li>
          {% endfor %}
          </ul>
      </div>
      <i class="clock icon"></i>
</div>



{% endblock %}


{% block content %}
{% if document.type == document.TYPE_DRAFT %}
<div class="ui yellow icon message">
      <i class="warning icon"></i>
      <div class="content">
        <p>
          Ce rapport est un brouillon, il n'est pas visible publiquement.
        </p>
      </div>
</div>
{% endif %}
<section class="ui row">
<h2>Services proposés aux adhérents</h2>

<p class="ui text container">
  Combien chaque abonnement à un service coûte à l'association ?
</p>

<ul class="ui text container">
{% for service in document.service_set.subscribables %}
  <li>
    <a href="{{ service.get_absolute_url }}">{{ service.name }}</a>
    ({{ service.get_prices.unit_consolidated_cost|price }} /mois)
  </li>
{% empty %}
  <li>Pas de service pour l'instant.</li>
{% endfor %}
</ul>

</section>

<section class="ui row">
<h2>Que paye {{ settings.ORGANIZATION_NAME }} chaque mois ?</h2>

<div class="ui text container">
<p>
Coûts facturés à l'association mensuellement pour fournir l'ensemble des services.
</p>

<table class="ui structured table">
  <thead>
    <tr>
      <th>Désignation</th><th>Forfait souscrit</th>
      <th>Coût mensuel</th>
    </tr>
  </thead>
  <tbody>

{% for cost in document.cost_set.all %}
    <tr>
      <td>
       {{ cost.name }}
        {% if cost.description %}
        <a href="#" title="{{ cost.description }}">
          <i class="info circle icon"></i>
        </a>
        {% endif %}
      </td>
      <td>
        {% if cost.capacity_unit %}
        {{ cost.total_capacity|human_round }} {{ cost.get_capacity_unit_display }}
        {% else %}
        n/a
        {% endif %}
      </td>
      <td>{{ cost.price|price }}</td>
    </tr>
{% empty %}
  <tr><td>Pas de coût pour l'instant.</td></tr>
{% endfor %}
  </tbody>
  <tfoot>
    <tr><th colspan="2">Total mensuel</th><th>{{ total_recuring_costs|price }}</th></tr>
  </tfoot>
</table>

</section>

<section class="ui row">
  <h2>Matériel et frais d'accès</h2>

  <div class="ui text container">
  <p>
    Sont listés ici les investissements que l'association n'a a payer qu'une
    fois. Le coût d'achat est réparti entre les différents services. De plus,
  chaque mois, de l'argent est mis de côté pour veiller au remplacement de ce
  matériel lorsque celui-ci arrivera en fin de vie (<em>
{{ document.good_set.monthly_provision_total|price }}</em> ce mois-ci).
    </p>
<table class="ui structured table">
  <thead>
    <tr>
      <th>Désignation</th>
      <th>Coût d'achat</th>
    </tr>
  </thead>
  <tbody>

{% for good in document.good_set.all %}
  <tr>
    <td>
     {{ good.name }}
      {% if good.description %}
      <a href="#" title="{{ good.description }}">
        <i class="info circle icon"></i>
      </a>
      {% endif %}
    </td>
    <td>
      {{good.price|price }}
    </td>
  </tr>
{% empty %}
  <tr><td>Pas de matériel pour l'instant.</td></tr>
{% endfor %}
  <tfoot>
    <tr><th>Total</th><th>{{ total_goods|price }}</th></tr>
  </tfoot>
</table>
</div>
</section>
{% endblock %}

costs/templates/costs/resources_list.html
<h1>Coûts récurents et amortissement</h1>

{% if costs.count > 0 %}

<h2>Coûts mensuels</h2>
<ul>
  {% for i in costs %}
  <li>{{ i.name }}</li>
  {% endfor %}
</ul>

{% else %}

<p>Pas de coûts mensuels définis pour l'instant</p>

{% endif %}

{% if goods.count > 0 %}

<h2>Matériel et frais d'accès amortis</h2>
<ul>
  {% for i in goods %}
  <li>{{ i.name }}</li>
  {% endfor %}
</ul>

{% else %}

<p>Pas de matériels ni frais d'accès définis pour l'instant</p>

{% endif %}

costs/templates/costs/service_detail.html
{% extends "base.html" %}

{% load costs %}

{% block rail %}

  <div class="ui tag labels">
    <div class="ui label blue">
      {{ service.subscriptions_count }}
      <div class="detail">abonnements</div>

    </div>
    <br>
  {% if document.type == document.TYPE_DRAFT %}
  <a class="ui label orange" title="Ce document se base sur des estimations">
    {{ document.get_type_display }}
  </a>
  {% else %}
  <span class="ui label">
    {{ document.get_type_display }}
    <div class="ui detail">{{ document.date|date:"b Y" }}</div>
  </span>
  {% endif %}
  </div>

  <div class="ui segment" style="width: 100%">
  <p>
    <a class="ui ribbon left label">Notes</a>
{{ service.description_html|safe }}
  </p>
  </div>
  <div class="ui vertical fluid menu">
  {% if request.user.is_staff %}
  <a href="{% url 'admin:costs_service_change' service.id %}" class="item">
    <i class="edit icon"></i>
    Éditer
  </a>
  {% endif %}
  </div>
{% endblock %}


{% block content %}
  {% if service.internal %}
  <div class="ui yellow icon message">
    <i class="warning icon"></i>
    <div class="content">
      <p>
        Ce service est utilisé en interne comme brique pour construire d'autres
  services ; il n'est pas ouvert tel quel aux abonnements.
      </p>
    </div>
  </div>
  {% endif %}

  <section class="text container ui row">
    <div class="ui icon message">
      <i class="money icon"></i>
      <div class="content">
        <div class="header">

        </div>
        <p>
          La fourniture d'un abonnements <em>{{ service.name }}</em> coûte <strong>{{ unit_consolidated_cost|price }}</strong> par mois à l'association.
        </p>
      </div>
    </div>
    <div class="segment">
      <p>
Ce détail du <em>coût de revient</em> vous permet de choisir le <strong>prix
  libre</strong> de votre abonnement.
      </p>
      <p>
Le but n'est pas que tout le monde paye le coût de revient, mais plutôt que chacun
contribue selon ses moyens financiers et sa volonté ; les personnes payant plus
  finançant <strong>solidairement</strong> le service pour ceux qui payent moins.
      </p>
      <p>
Outre le coût mensuel, il est important de noter que <strong>l'association a
besoin d'une marge</strong> pour développer son activité, lancer de nouveaux
chantiers, et parer aux imprévus. Bien qu'elle n'apparaisse pas ici, il est
  donc nécessaire d'inclure cette marge dans votre calcul.
      </p>
    </div>
  </section>


  <table class="ui celled  table">
    <thead>
      <tr><th>Désignation</th><th class="right aligned">Coût mensuel par abonnement</th></tr>
    </thead>
    <tbody>
      <tr>
        <td>
          + Coût mensuel
          <a href="#recuring-details"><i class="info yellow circle icon" title="Détails"></i></a>
        </td>
        <td class="right aligned">{{ unit_recurring_price|price }}</td>
      </tr>
      <tr>
        <td>
          + Coût de mise service (réparti sur 36 mois)
          <a href="#setup-details"><i class="info green circle icon"></i></a>
        </td>
        <td class="right aligned">{{ unit_staggered_goods_share|price }}</td>
      </tr>
    </tbody>
    <tfoot>
      <tr>
        <th><strong>= Coût mensuel total</strong></th><th class="right aligned"><strong>{{ unit_consolidated_cost|price }}</strong></th>
      </tr>
    </tfoot>
    </table>

  <h2 id="recuring-details"><i class="info yellow circle icon"></i>Détail des coûts mensuels</h2>

  <section class="ui row">

    <div class="ui text container">
  <p>
    <em>L'amortissement</em> permet à l'association d'anticiper le renouvellement du matériel lorsqu'il casse ou devient obsolète.
  </p>
  <p>
   Le <em>récurrent</em> correspond aux coûts que l'association doit payer chaque mois à ses fournisseurs.
  </p>
    </div>

  <table class="ui celled structured table">
    <thead>
      <tr>
        <th>Type</th><th>Nom</th><th class="right aligned">Coût mensuel <br> (par abonnement)</th>
      </tr>
    </thead>
    <tbody>
  {% for usage in costs_uses %}
      <tr>
      {% if forloop.first %}
        <td rowspan="{{ costs_uses|length }}">Récurrent</td>
      {% endif %}
        <td>
      {{ usage.resource.name }}
          <span class="bare-info">
               {% if usage.resource.capacity_unit %}
           ({{ usage.unit_share|human_round }} {{ usage.resource.get_capacity_unit_display }})
         {% else %}
           ({{ usage.unit_real_share|percent }})
         {% endif %}
          </span>
        </td>
        <td class="right aligned">{{ usage.unit_cost_share|price }}</td>
      </tr>
  {% endfor %}
  {% for usage in services_uses %}
      <tr>
      {% if forloop.first %}
        <td rowspan="{{ costs_uses|length }}">Récurrent (service)</td>
      {% endif %}
        <td>
          <a href="{{ usage.resource.get_absolute_url }}">service {{ usage.resource.name }}</a>
          <span class="bare-info">
         {% if usage.resource.capacity_unit %}
           ({{ usage.unit_share|human_round }} {{ usage.resource.get_capacity_unit_display }})
         {% else %}
           ({{ usage.unit_real_share|percent }})
         {% endif %}
          </span>
        </td>
        <td class="right aligned">{{ usage.unit_cost_share|price }}</td>
      </tr>
  {% endfor %}
  {% for usage in goods_uses %}
      <tr>
      {% if forloop.first %}
        <td rowspan="{{ goods_uses|length }}">Amortissement</td>
      {% endif %}
        <td>
       {{ usage.resource.name }}
          <span class="bare-info">
       {% if usage.resource.capacity_unit %}
           ({{ usage.unit_share|human_round }} {{ usage.resource.get_capacity_unit_display }})
         {% else %}
           ({{ usage.unit_real_share|percent }})
         {% endif %}
          </span>
        </td>
        <td class="right aligned">{{ usage.unit_monthly_provision_share|price }}</td>
      </tr>
  {% endfor %}
    </tbody>
  </table>
</section>
  <h2 id="setup-details"><i class="info green circle icon"></i>Détail des coûts de mise en service</h2>


<section class="ui row">

  <div class="ui text container">
    <p>
      Des coûts ont lieu au moment de la mise en service d'un nouvel abonnement (ex: achat de matériel). Afin d'éviter un coût trop important pour l'adhérent, l'association propose d'étaler ce coût sur 3 ans.
    </p>
    <p>
      Libre à vous, si vous souhaitez aider la trésorie de l'asso de payer vos 6 premiers mois de l'abonnement d'un coup.
    </p>
  </div>
  <table class="ui celled structured table">
    <thead>
      <tr>
        <th>Nom</th><th>Coût (par nouvel abonnement)</th>
      </tr>
    </thead>
    <tbody>
{% for good_use in goods_uses %}
      <tr>
        <td>{{ good_use.resource.name }}</td>
        <td>{{ good_use.unit_value_share|price }}</td>
      </tr>
{% endfor %}
{% for service_use in services_uses %}
      <tr>
        <td>
          FAS service
          <a href="{{ service_use.resource.get_absolute_url }}">
            {{ service_use.resource.name }}
          </a>
        </td>
        <td>{{ service_use.unit_value_share|price }}</td>
      </tr>
{% endfor %}

    </tbody>
  </table>

  <p class="ui text container"></p>

</section>

{% endblock %}

costs/templates/costs/services_list.html
{% if services.count > 0 %}

<ul>
  {% for i in services %}
  <li><a href="{{ i.get_absolute_url }}">{{ i.name }}</a></li>
  {% endfor %}
</ul>

{% else %}

<p>Pas de services définis pour l'instant</p>

{% endif %}